#ifndef __DEFINITIONS_H__
#define __DEFINITIONS_H__

#define DISPLAY_TIME_SPLASH_SCENE 0
#define TRANSITION_TIME 0.5
#define INIT_SPACESHIP_ORBIT 100
#define SNAKE_LENGTH 1
#define LEVEL_COUNT 6
#define NO_OF_SCROLL_PANES 1
#define HEIGHT_DIVISION_FACTOR 6
#define COMPILE_FOR_MOBILE 1
#endif // __DEFINITIONS_H__
